name: CI

on:
  push:
  pull_request:

jobs:
  test-imports:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install gradio numpy pandas matplotlib scipy joblib scikit-learn

      - name: Import test
        run: |
          python - << EOF
          import gradio
          import numpy
          import pandas
          import matplotlib
          import scipy
          import joblib
          print("All imports OK")
          EOF
